import json
import os
from pathlib import Path

import faiss
import numpy as np

INDEX_PATH = Path("mines_index.faiss")
METADATA_PATH = Path("metadata.json")
TOP_K = 3
HF_CACHE_DIR = Path(".hf-cache")
LOCAL_MODELS_DIR = Path(".models")
MODEL_REQUIRED_FILES = (
    "config.json",
    "modules.json",
    "sentence_bert_config.json",
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.txt",
    "1_Pooling/config.json",
)
MODEL_WEIGHT_FILES = ("model.safetensors", "pytorch_model.bin")

os.environ.setdefault("HF_HOME", str(HF_CACHE_DIR.resolve()))
os.environ.setdefault("SENTENCE_TRANSFORMERS_HOME", str(HF_CACHE_DIR.resolve()))
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")

from sentence_transformers import SentenceTransformer
from huggingface_hub import snapshot_download


def load_metadata(path: Path) -> dict:
    """Load metadata generated by build_rag.py."""
    if not path.exists():
        raise FileNotFoundError(f"Metadata file not found: {path}")

    return json.loads(path.read_text(encoding="utf-8"))


def load_faiss_index(path: Path) -> faiss.Index:
    """Load the FAISS vector index from disk."""
    if not path.exists():
        raise FileNotFoundError(f"FAISS index not found: {path}")

    return faiss.read_index(str(path))


def get_model_path(model_name: str) -> str:
    """Return a local model path, downloading without symlinks if needed."""
    local_path = LOCAL_MODELS_DIR / model_name
    has_required_files = all((local_path / file).exists() for file in MODEL_REQUIRED_FILES)
    has_weights = any((local_path / file).exists() for file in MODEL_WEIGHT_FILES)
    if local_path.exists() and has_required_files and has_weights:
        return str(local_path)

    local_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot_download(
        repo_id=f"sentence-transformers/{model_name}",
        local_dir=str(local_path),
        local_dir_use_symlinks=False,
        allow_patterns=[
            "config.json",
            "modules.json",
            "sentence_bert_config.json",
            "tokenizer.json",
            "tokenizer_config.json",
            "vocab.txt",
            "special_tokens_map.json",
            "model.safetensors",
            "pytorch_model.bin",
            "1_Pooling/config.json",
        ],
    )
    return str(local_path)


def embed_question(question: str, model_name: str) -> np.ndarray:
    """Convert a user question into a normalized embedding."""
    model = SentenceTransformer(get_model_path(model_name))
    embedding = model.encode(
        [question],
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return embedding.astype("float32")


def retrieve(question: str, index: faiss.Index, metadata: dict, top_k: int = TOP_K) -> list[dict]:
    """Retrieve the top-k most relevant chunks for a question."""
    if not question.strip():
        raise ValueError("Question cannot be empty")

    model_name = metadata.get("model_name")
    if not model_name:
        raise ValueError("metadata.json does not contain model_name")

    query_embedding = embed_question(question, model_name)
    scores, ids = index.search(query_embedding, top_k)

    chunks = metadata.get("chunks", [])
    results = []
    for rank, (chunk_id, score) in enumerate(zip(ids[0], scores[0]), start=1):
        if chunk_id < 0:
            continue
        if chunk_id >= len(chunks):
            raise IndexError(f"FAISS returned invalid chunk id: {chunk_id}")

        chunk = chunks[chunk_id]
        results.append(
            {
                "rank": rank,
                "score": float(score),
                "source": chunk["source"],
                "path": chunk["path"],
                "text": chunk["text"],
            }
        )

    return results


def print_results(question: str, results: list[dict]) -> None:
    """Print retrieved chunks clearly in the terminal."""
    print("\n" + "=" * 80)
    print(f"Question: {question}")
    print("=" * 80)

    if not results:
        print("No relevant chunks found.")
        return

    for result in results:
        print(f"\n[{result['rank']}] Score: {result['score']:.4f}")
        print(f"Source: {result['source']}")
        print("-" * 80)
        print(result["text"])
        print("-" * 80)


def main() -> None:
    try:
        metadata = load_metadata(METADATA_PATH)
        index = load_faiss_index(INDEX_PATH)

        question = " ".join(__import__("sys").argv[1:]).strip()
        if not question:
            question = input("Question: ").strip()

        results = retrieve(question, index, metadata, TOP_K)
        print_results(question, results)
    except Exception as exc:
        print(f"Error while querying RAG index: {exc}")
        raise


if __name__ == "__main__":
    main()
