import json
import os
from pathlib import Path

import faiss
import numpy as np
import openai
from typing import Tuple

INDEX_PATH = Path("mines_index.faiss")
            results = retrieve(question, index, metadata, TOP_K)
            # Synthesize final answer using LLM and print JSON
            try:
                synth = synthesize_answer(question, results)
            except Exception as exc:
                print(f"Error while calling LLM: {exc}")
                # Fallback: print retrieved results
                print_results(question, results)
                return

            print(json.dumps(synth, ensure_ascii=False, indent=2))
HF_CACHE_DIR = Path(".hf-cache")
LOCAL_MODELS_DIR = Path(".models")
MODEL_REQUIRED_FILES = (
    "config.json",
    "modules.json",
    "sentence_bert_config.json",
    "tokenizer.json",
    "tokenizer_config.json",
    "vocab.txt",
    "1_Pooling/config.json",
)
MODEL_WEIGHT_FILES = ("model.safetensors", "pytorch_model.bin")

os.environ.setdefault("HF_HOME", str(HF_CACHE_DIR.resolve()))
os.environ.setdefault("SENTENCE_TRANSFORMERS_HOME", str(HF_CACHE_DIR.resolve()))
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")

from sentence_transformers import SentenceTransformer
from huggingface_hub import snapshot_download


def load_metadata(path: Path) -> dict:
    """Load metadata generated by build_rag.py."""
    if not path.exists():
        raise FileNotFoundError(f"Metadata file not found: {path}")

    return json.loads(path.read_text(encoding="utf-8"))


def load_faiss_index(path: Path) -> faiss.Index:
    """Load the FAISS vector index from disk."""
    if not path.exists():
        raise FileNotFoundError(f"FAISS index not found: {path}")

    return faiss.read_index(str(path))


def get_model_path(model_name: str) -> str:
    """Return a local model path, downloading without symlinks if needed."""
    local_path = LOCAL_MODELS_DIR / model_name
    has_required_files = all((local_path / file).exists() for file in MODEL_REQUIRED_FILES)
    has_weights = any((local_path / file).exists() for file in MODEL_WEIGHT_FILES)
    if local_path.exists() and has_required_files and has_weights:
        return str(local_path)

    local_path.parent.mkdir(parents=True, exist_ok=True)
    snapshot_download(
        repo_id=f"sentence-transformers/{model_name}",
        local_dir=str(local_path),
        local_dir_use_symlinks=False,
        allow_patterns=[
            "config.json",
            "modules.json",
            "sentence_bert_config.json",
            "tokenizer.json",
            "tokenizer_config.json",
            "vocab.txt",
            "special_tokens_map.json",
            "model.safetensors",
            "pytorch_model.bin",
            "1_Pooling/config.json",
        ],
    )
    return str(local_path)


def embed_question(question: str, model_name: str) -> np.ndarray:
    """Convert a user question into a normalized embedding."""
    model = SentenceTransformer(get_model_path(model_name))
    embedding = model.encode(
        [question],
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return embedding.astype("float32")


def retrieve(question: str, index: faiss.Index, metadata: dict, top_k: int = TOP_K) -> list[dict]:
    """Retrieve the top-k most relevant chunks for a question."""
    if not question.strip():
        raise ValueError("Question cannot be empty")

    model_name = metadata.get("model_name")
    if not model_name:
        raise ValueError("metadata.json does not contain model_name")

    query_embedding = embed_question(question, model_name)
    scores, ids = index.search(query_embedding, top_k)

    chunks = metadata.get("chunks", [])
    results = []
    for rank, (chunk_id, score) in enumerate(zip(ids[0], scores[0]), start=1):
        if chunk_id < 0:
            continue
        if chunk_id >= len(chunks):
            raise IndexError(f"FAISS returned invalid chunk id: {chunk_id}")

        chunk = chunks[chunk_id]
        results.append(
            {
                "rank": rank,
                "score": float(score),
                "source": chunk["source"],
                "path": chunk["path"],
                "text": chunk["text"],
            }
        )

    return results


def print_results(question: str, results: list[dict]) -> None:
    """Print retrieved chunks clearly in the terminal."""
    print("\n" + "=" * 80)
    print(f"Question: {question}")
    print("=" * 80)

    if not results:
        print("No relevant chunks found.")
        return

    for result in results:
        print(f"\n[{result['rank']}] Score: {result['score']:.4f}")
        print(f"Source: {result['source']}")
        print("-" * 80)
        print(result["text"])
        print("-" * 80)


# --- LLM synthesis ---------------------------------------------------------
PROMPT_TEMPLATE = """
Vous êtes un assistant professionnel qui répond en français de façon concise et claire.
Vous avez à disposition uniquement les extraits fournis ci-dessous (Contexte).
Répondez à la question en utilisant exclusivement ces extraits. Ne supposez rien qui ne soit pas dans le contexte.
Si la réponse n'est pas dans le contexte, répondez honnêtement "Je ne sais pas" ou "Aucune information disponible dans les documents fournis".

Instructions strictes :
- Rédigez la réponse en français, ton professionnel et concis (3-6 phrases maximum si possible).
- Incluez des citations entre crochets indiquant la source exacte utilisée, par exemple [ITIE_Mali_Rapport_2019_chunk_0001.txt].
- Après la réponse, fournissez la liste des sources utilisées sous la clé `sources` (format JSON demandé).
- N'utilisez PAS d'informations en dehors des extraits fournis.

Format de sortie (strictement) :
{\n  "answer": "...texte en français...",\n  "sources": ["source1", "source2"]\n}

Contexte :\n{context}\n\nQuestion : {question}
"""


def synthesize_answer(question: str, results: list[dict],
                      model: str | None = None,
                      temperature: float = 0.0) -> dict:
    """Synthesize a concise French answer from retrieved chunks using OpenAI.

    Returns a dict with keys `answer` (str) and `sources` (list[str]).
    """
    if not results:
        return {"answer": "Aucune information disponible dans les documents fournis.", "sources": []}

    # Build context from retrieved chunks (keep order)
    context_items = []
    sources = []
    for r in results:
        src = r.get("source") or r.get("path") or "unknown"
        # avoid duplicate sources in list
        if src not in sources:
            sources.append(src)
        # include small header for each chunk
        context_items.append(f"Source: {src}\n{r.get('text','')}")

    context = "\n\n---\n\n".join(context_items)

    prompt = PROMPT_TEMPLATE.format(context=context, question=question)

    openai.api_key = os.environ.get("OPENAI_API_KEY")
    if openai.api_key is None:
        raise EnvironmentError("OPENAI_API_KEY not set in environment")

    model = model or os.environ.get("OPENAI_MODEL", "gpt-3.5-turbo")

    # Call the ChatCompletion API
    try:
        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": "Vous êtes un assistant utile et factuel qui répond uniquement avec des informations tirées du contexte fourni."},
                {"role": "user", "content": prompt},
            ],
            temperature=temperature,
            max_tokens=600,
        )
    except Exception as exc:
        raise RuntimeError(f"LLM request failed: {exc}")

    text = response.choices[0].message.content.strip()

    # Try to parse JSON from model output. If parsing fails, fall back to wrapping text.
    try:
        parsed = json.loads(text)
        # Ensure it has answer and sources
        ans = parsed.get("answer") or parsed.get("response") or parsed.get("text") or ""
        srcs = parsed.get("sources") or sources
        return {"answer": ans, "sources": srcs}
    except Exception:
        # Attempt to extract sources by intersecting known sources
        used = [s for s in sources if s in text]
        return {"answer": text, "sources": used}


def main() -> None:
    try:
        metadata = load_metadata(METADATA_PATH)
        index = load_faiss_index(INDEX_PATH)

        question = " ".join(__import__("sys").argv[1:]).strip()
        if not question:
            question = input("Question: ").strip()

        results = retrieve(question, index, metadata, TOP_K)
        print_results(question, results)
    except Exception as exc:
        print(f"Error while querying RAG index: {exc}")
        raise


if __name__ == "__main__":
    main()
